version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub

  open-browser-module:
    image: avgulavani/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BBROWSER=chrome
      - HUB_HOST=hub
      - MODULE=testng.xml
      - CUCUMBER_OPTIONS=classpath:featureFiles/open_browser.feature
    volumes:
      - ./open-browser-test-result:/usr/share/dockerdemo/test-output
  simple-featurefile-test-module:
    image: avgulavani/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BBROWSER=firefox
      - HUB_HOST=hub
      - MODULE=testng.xml
      - CUCUMBER_OPTIONS=classpath:featureFiles/sample.feature
    volumes:
      - ./sample-test-result:/usr/share/dockerdemo/test-output